name: "build-eap-action"
description: "Build the .eap package for an Axis ACAP"

inputs:
  dir:
    description: "The path to the project dir that should be built"
    default: "."
  arch:
    description: "The architecture to build for"
    default: ""
  libs:
    description: "Comma separated list of libraries to use"
    default: ""
  token:
    description: "The FixedIT access token"
    required: true
  fappcli-version:
    description: "The version of fappcli to use"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install fappcli
      uses: fixedit-ai/install-fappcli-action@main
      with:
        token: ${{ inputs.token }}
        fappcli-version: ${{ inputs.fappcli-version }}
    - name: Build application
      shell: bash
      run: |
        ARCH_ARG=`[[ -n "${{ inputs.arch }}" ]] && echo "--arch ${{ inputs.arch }}" || echo ""`
        LIBS=`echo ${{ inputs.libs }} | tr "," "\n" | awk '{print "--lib "$1}' | paste -sd " " -`
        LIBS_ARGS=`[[ -n "${{ inputs.libs }}" ]] && echo $LIBS || echo ""`
        fappcli-build build ${{ inputs.dir }} $ARCH_ARG $LIBS_ARGS