name: "build-eap-action"
description: "Build the .eap package for an Axis ACAP"

inputs:
  dir:
    description: "The path to the project dir that should be built"
    default: "."
  fapp-manifest:
    description: "The path to the fapp-manifest.json file to use"
    default: "fapp-manifest.json"
  arch:
    description: "The architecture to build for"
    default: ""
  libs:
    description: "Comma separated list of libraries to use"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Build application
      shell: bash
      run: |
        ARCH_ARG=`[[ -n "${{ inputs.arch }}" ]] && echo "--arch ${{ inputs.arch }}" || echo ""`
        LIBS=`echo ${{ inputs.libs }} | tr "," "\n" | awk '{print "--lib "$1}' | paste -sd " " -`
        LIBS_ARGS=`[[ -n "${{ inputs.libs }}" ]] && echo $LIBS || echo ""`
        fappcli-build build ${{ inputs.dir }} $ARCH_ARG $LIBS_ARGS --fapp-manifest ${{ inputs.fapp-manifest }}